name: GET/@waka-readme

on:
  schedule:
    - cron: "0 */3 * * *" # Runs every 3 hours
  workflow_dispatch: 

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          LANG_COUNT: 10
          SHOW_TIME: true
          IGNORED_LANGUAGES: XML YAML JSON TOML Markdown Other
          COMMIT_MESSAGE: "docs: @waka-readme update new metrics"
